# Generated by Django 2.0.3 on 2018-04-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=16)),
                ('longitude', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='path',
            name='station_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_a', to='rest_api.Station'),
        ),
        migrations.AddField(
            model_name='path',
            name='station_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_b', to='rest_api.Station'),
        ),
    ]
